### ISSUE TITLE
用户退出登录后，打开app仍然需要输入手势密码解锁

### ISSUE THREAD

**Issue by eyestone** [eyestone/welfare-ios-outsource#11]
用户退出登录后，打开app仍然需要输入手势密码解锁

退出登陆后，手势密码就应该一起删除

**Comment by pencilSharp** [comment]
退出登录后删除了loginCode。这样打开app就不会再出现自动登录  
问题中所说的 ：“打开app仍然需要输入手势密码解锁”。这里是手势密解锁还是设置手势密码。我看到的问题是设置手势密码。

**Comment by eyestone** [comment]
就是用户如果退出账号之后，那么就应该删除手势。

但是我测试发现退出账号后，仍然要弹出手势密码界面要求输入

**Comment by pencilSharp** [comment]
已经修改 laifu0512

**Comment by eyestone** [comment]
Test OK
