### ISSUE TITLE
忘记密码，找回功能无法找回

### ISSUE THREAD

**Issue by eyestone** [eyestone/welfare-ios-outsource#12]
找回密码，第一步输入基本信息，提交，能收到短信 -------------- OK
根据短信验证码输入更改密码，提交成功，但是用新密码无法登陆 ---------------NOK

我看到数据库是明文，存新密码也需要md5之后插入

**Comment by pencilSharp** [comment]
已经修正

**Comment by eyestone** [comment]
Test OK
