### ISSUE TITLE
用户激活尚未实现

### ISSUE THREAD

**Issue by eyestone** [eyestone/welfare-ios-outsource#13]
用户激活尚未实现
完全不可用
第一个界面点击下一步就没有任何反应

**Comment by pencilSharp** [comment]
已经激活的测试账户，不能再激活查看下一步的界面。未激活的测试账户，还需要知道其他的相关信息：邮箱，身份证号，手机号等。  所以为了测试方面，看能不能让我有权限修改 hubin1那个账号的激活状态。

**Comment by pencilSharp** [comment]
![2015-05-11 3 45 33](https://cloud.githubusercontent.com/assets/12379732/7560344/e05b9c5e-f7f4-11e4-9a84-b78842e71488.png)
激活账户第二部UI

**Comment by pencilSharp** [comment]
![2015-05-11 4 43 36](https://cloud.githubusercontent.com/assets/12379732/7561231/06d42af6-f7fd-11e4-8516-d86f87c57c9b.png)
提交数据部分已经完成，需要一个未激活的，知道相关信息的测试账号。

**Comment by eyestone** [comment]
胡斌2
18668098398
13880676776@163.com
370281197811137612

激活短信，你发送之后，找我问

**Comment by eyestone** [comment]
今天我测了下，激活可以成功

还有点细节需要修改：
1. 激活成功后，应该跳回登录界面，而不是第一步的界面。
2. 第一步和第二步，点击按钮提交的时候，都需要有个加载效果，不然用户看起来点没点到都不晓得，还有可能出现重复提交

**Comment by pencilSharp** [comment]
已经修复

**Comment by eyestone** [comment]
等你们发了新版本再看看
