### ISSUE TITLE
登录界面与设计完全不同，显示效果很差

### ISSUE THREAD

**Issue by eyestone** [eyestone/welfare-ios-outsource#2]
登录界面与设计完全不同，显示效果很差

需要优化
![2015 5 7_1713 6](https://cloud.githubusercontent.com/assets/8198825/7512035/746e4d04-f4dc-11e4-9c4a-a614c927b2c8.png)

**Comment by pencilSharp** [comment]
已经完成修改

**Comment by eyestone** [comment]
可能还要调整下，一是背景色，只有上面一块灰色
二是下面的绿色字体，太小

**Comment by pencilSharp** [comment]
已经修改
![2015-05-11 2 50 06](https://cloud.githubusercontent.com/assets/12379732/7559690/3c981374-f7ed-11e4-856a-3ec22caccbf8.png)

**Comment by eyestone** [comment]
比之前好多了。

另外就是，那天马总说，绿色的字颜色有点不合适。
你们参看下android上的颜色吧

**Comment by pencilSharp** [comment]
![2015-05-18 2 49 47](https://cloud.githubusercontent.com/assets/12379732/7675625/2ac8be2a-fd6d-11e4-9164-93eb30bcf583.png)
完成修改

**Comment by eyestone** [comment]
等发了版本测试看

**Comment by eyestone** [comment]
Test OK
20150521

**Comment by eyestone** [comment]
那个亮绿色的问题，还有很多界面的绿色是以前的亮绿色，需要改成和登陆界面相同的绿色

**Comment by pencilSharp** [comment]
已经修改

**Comment by eyestone** [comment]
Test OK
