### ISSUE TITLE
“我的”界面显示效果较差

### ISSUE THREAD

**Issue by eyestone** [eyestone/welfare-ios-outsource#4]
“我的”界面：

1. 所有图标基本都显示较为模糊
2. 功能按钮圆形变成了椭圆
3. 功能文字较小，不匹配
4. 来福卡上面文字区域空白
等等，需要调整

**Comment by pencilSharp** [comment]
除了第4条外，完成修改。第4条中的文字和数字是固定的还是从网上获取的呢？之前观察hubin1账号和wanghao账号的时候，他们显示的内容都是一样的。

**Comment by eyestone** [comment]
文字肯定是固定的
数字是根据卡号动态显示的

卡号登录的时候会返回， aipLoginId这个参数就是

**Comment by eyestone** [comment]
另外，右上角那个图标看起来也比较模糊，调整下

**Comment by pencilSharp** [comment]
![2015-05-11 9 44 15](https://cloud.githubusercontent.com/assets/12379732/7565991/f45fa47a-f826-11e4-92b9-fae2487fc1e6.png)
添加来福卡信息

**Comment by pencilSharp** [comment]
![2015-05-11 9 45 46](https://cloud.githubusercontent.com/assets/12379732/7566017/2449457e-f827-11e4-8e8b-de9b427269fe.png)
添加来福卡信息

**Comment by eyestone** [comment]
比之前好多了，还有点问题哈。

android版上，相当于背景是灰色的一块，卡和按钮时在灰色背景上。
按钮区域是白色背景，上下都没有分隔线。

在稍微调整下吧

**Comment by pencilSharp** [comment]
![2015-05-19 10 18 51](https://cloud.githubusercontent.com/assets/12379732/7694266/a0560348-fe10-11e4-91b0-9db21e1883b5.png)
完成调整

**Comment by eyestone** [comment]
Test OK
20150521
