### ISSUE TITLE
修改登录密码功能问题

### ISSUE THREAD

**Issue by eyestone** [eyestone/welfare-ios-outsource#8]
1. 修改密码提示失败，但是实际已经修改成功，需用新密码登录
2. 修改失败的提示始终存在，无法小时，也无法做其他操作，只有退出app重新进

**Comment by pencilSharp** [comment]
已经修改

**Comment by eyestone** [comment]
还有点问题，修改成功还是弹出提示。
而且提示框一直不消。

App无法操作了

**Comment by pencilSharp** [comment]
是账号设置里面，修改出现这个问题。还是忘记密码里面修改出现这个问题呢？ 账号设置里修改密码，我测了没问题

**Comment by eyestone** [comment]
我说了啊，修改提交，提示成功的文本框。

我刚才又试了下，不是每次都会出现，但是有一定概率出现。
最开始一次就出来了
刚才试了三次才出现

**Comment by eyestone** [comment]
![image](https://cloud.githubusercontent.com/assets/8198825/7675118/c80bb4be-fd66-11e4-8957-44d542ebdbe6.png)

**Comment by eyestone** [comment]
今天用最新版本测试，还是会出现这个现象
见截图

**Comment by eyestone** [comment]
今天的版本还是有这个问题。

我发现问题的关键在哪了。

如果用户连续点击两次提交，就会出现卡死。

对于点击提交，都需要处理连点的问题。

**Comment by pencilSharp** [comment]
bug无法复现

**Comment by eyestone** [comment]
Test OK
